version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: health_system
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  api-gateway:
    build: ./services/api-gateway
    depends_on:
      - rabbitmq
      - postgres
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      DATABASE_URL: postgres://admin:password@postgres:5432/health_system
    ports:
      - "3000:3000"
